"use client";

import { useState } from "react";
import { RefreshCw, ChevronDown, ChevronUp } from "lucide-react";

type TraceFields = {
  t: string;
  r: string;
  a: string;
  c: string;
  e: string;
};

type Props = {
  value: string;
  onChange: (notes: string) => void;
};

const TIPS = [
  "AI generates text by predicting patterns — it doesn't reason or know things. Confident language is not a signal of accuracy.",
  "Use AI after you've formed your own view — to test it, complicate it, or find what you missed. Not to form the view for you.",
  "If you couldn't write this entry without AI, that's a signal: put it down and write first.",
  "Ask AI to challenge your thinking: 'What are the strongest objections to this?' 'Who is missing from this analysis?'",
  "Reflective writing generated by AI isn't reflection — it's simulation of reflection. Your portfolio documents your development.",
  "AI training data skews toward English-language, Western, and institutional knowledge. Use it critically in regenerative and Indigenous contexts.",
  "Be transparent: if AI shaped your thinking or writing, say so in your declaration and in any work you submit.",
  "Productive struggle is how learning happens. Using AI to avoid difficulty is using it to avoid growth.",
  "Never present AI-generated text as your own reflection or analysis without attribution.",
  "AI has no awareness of stakes or consequences — the judgment about what matters is yours to apply.",
  "In community-based contexts, AI cannot hold relationship, reciprocity, or responsibility. Engage directly with people and place.",
  "Large language models consume significant energy and water. Use them deliberately, not habitually.",
];

const TRACE_FIELDS: { key: keyof TraceFields; letter: string; label: string; placeholder: string }[] = [
  {
    key: "t",
    letter: "T",
    label: "Tool",
    placeholder: "Which AI tool(s) did you use? (e.g. ChatGPT, Claude, Copilot, image generator…)",
  },
  {
    key: "r",
    letter: "R",
    label: "Rationale & Role",
    placeholder: "Why did you use it, and what role did it play? (e.g. brainstorming, drafting, research, checking your reasoning)",
  },
  {
    key: "a",
    letter: "A",
    label: "Assessment of Output",
    placeholder: "How accurate and useful was the output? Did you verify claims or data against other sources?",
  },
  {
    key: "c",
    letter: "C",
    label: "Critical Evaluation",
    placeholder: "What did you accept, reject, or modify from the AI output — and why?",
  },
  {
    key: "e",
    letter: "E",
    label: "Ethical Considerations",
    placeholder: "Any concerns about bias, missing perspectives, attribution, or appropriate use in this context?",
  },
];

function parse(raw: string): TraceFields {
  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === "object" && "t" in parsed) return parsed as TraceFields;
  } catch {
    // not JSON
  }
  return { t: "", r: "", a: "", c: "", e: "" };
}

export default function AiUsePanel({ value, onChange }: Props) {
  const [fields, setFields] = useState<TraceFields>(() => parse(value));
  const [tipIndex, setTipIndex] = useState(() => Math.floor(Math.random() * TIPS.length));
  const [showAll, setShowAll] = useState(false);

  function updateField(key: keyof TraceFields, val: string) {
    const next = { ...fields, [key]: val };
    setFields(next);
    onChange(JSON.stringify(next));
  }

  const hasAnyContent = Object.values(fields).some((v) => v.trim().length > 0);

  return (
    <div className="space-y-4">
      {/* Rotating tip */}
      <div className="rounded-lg bg-[#000054]/5 border border-[#000054]/10 p-3 space-y-2">
        <p className="text-xs font-medium text-[#000054]/60 uppercase tracking-wide">
          Using AI well
        </p>
        <p className="text-xs text-gray-700 leading-relaxed">
          {TIPS[tipIndex]}
        </p>
        <button
          onClick={() => setTipIndex((i) => (i + 1) % TIPS.length)}
          className="flex items-center gap-1 text-xs text-gray-400 hover:text-gray-600 transition-colors"
        >
          <RefreshCw size={10} />
          another tip
        </button>
      </div>

      {/* TRACE fields */}
      <div className="space-y-3">
        {!hasAnyContent && (
          <p className="text-xs text-gray-400">
            If you used AI for this entry, complete the fields below. If not, leave them blank.
          </p>
        )}
        {TRACE_FIELDS.map(({ key, letter, label, placeholder }) => (
          <div key={key}>
            <label className="flex items-baseline gap-1.5 mb-1">
              <span className="text-xs font-bold text-[#000054]">{letter}</span>
              <span className="text-xs font-medium text-gray-600">{label}</span>
            </label>
            <textarea
              value={fields[key]}
              onChange={(e) => updateField(key, e.target.value)}
              placeholder={placeholder}
              rows={2}
              className="w-full text-xs border border-gray-200 rounded-lg px-2.5 py-2 resize-none focus:outline-none focus:ring-1 focus:ring-gray-300 bg-white placeholder-gray-300 leading-relaxed"
            />
          </div>
        ))}
      </div>

      {/* All tips — collapsed by default */}
      <div>
        <button
          onClick={() => setShowAll((v) => !v)}
          className="flex items-center gap-1 text-xs text-gray-400 hover:text-gray-600 transition-colors"
        >
          {showAll ? <ChevronUp size={11} /> : <ChevronDown size={11} />}
          {showAll ? "Hide guidance" : "Guidance on responsible AI use"}
        </button>
        {showAll && (
          <ul className="mt-3 space-y-2">
            {TIPS.map((tip, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="shrink-0 w-1 h-1 rounded-full bg-gray-300 mt-1.5" />
                <p className="text-xs text-gray-500 leading-relaxed">{tip}</p>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
